server:
  port: 8080

spring:
  application:
    name: estoque

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml